language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true

script:
  - go vet ./...
  - go test -v ./... -cover -coverprofile=coverage.txt -covermode=atomic
  - go tool cover -html=coverage.txt -o coverage.html
after_success:
  - bash <(curl -s https://codecov.io/bash)
